name: VPS with Tailscale

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled --state=mem:/tmp/tailscaled.state --socket=/tmp/tailscaled.sock &
          sleep 5
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-vps

      - name: Setup SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo useradd -m vpsuser
          echo 'vpsuser:vpspass' | sudo chpasswd
          sudo service ssh start

      - name: Show IP
        run: |
          tailscale ip -4
