
name: Shell

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Sshx
        run: |
          curl -sSf https://sshx.io/get | sh -s run
                    
