name: Windows - RustDesk
on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing
        run: |
          Invoke-WebRequest -Uri "https://..." -OutFile "Downloads.bat"
          cmd /c Downloads.bat
      - name: Log In To AnyDesk
        run: cmd /c show.bat
      - name: Time Counter
        run: python -c "exec('import time; while True: time.sleep(1)')"
        
