name: GitHub Actions SSH with Tailscale

on:
  workflow_dispatch:

jobs:
  ssh-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Cài Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TS_AUTH_KEY }} --ssh

      - name: Tạo user SSH
        run: |
          sudo useradd -m github && echo "github:123456" | sudo chpasswd
          sudo usermod -aG sudo github
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Giữ cho job chạy 6h
        run: sleep 21600

         # Keep runner active indefinitely (or until manually cancelled)
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
